In [1]:
import torch

In [2]:
torch.Tensor([[0,1],[0,1]])

tensor([[0., 1.],
        [0., 1.]])

In [4]:
a = torch.Tensor([0])
b = torch.Tensor([1])

In [5]:
torch.cat([a,b]) # concate

tensor([0., 1.])

In [10]:
c = torch.Tensor([[0],[1]])
d = torch.Tensor([[0,1],[0,1]])

In [27]:
c_t = torch.transpose(c,0,1)

In [29]:
c @ c_t

tensor([[0., 0.],
        [0., 1.]])

In [30]:
c_t @ c

tensor([[1.]])

In [17]:
d @ c # matmul

tensor([[1.],
        [1.]])